### ISSUE TITLE
When executing encountering "HTTP request failed with err: invalid character '<' looking for beginning of value."

### ISSUE THREAD

**Issue by EmbeddedBacon** [cedricblondeau/world-cup-2022-cli-dashboard#16]
When launching the dashboard using "~/go/bin/world-cup-2022-cli-dashboard" the program displays

 ❌ HTTP request failed with err: invalid character '<' looking for beginning of value.  
 
 version of go is go 1.19.3 linux/amd64

**Comment by DannyJJK** [comment]
Are you using the worldcupjson.net API? It looks like it's possibly getting HTML from the API response instead of the expected JSON. Try visiting https://worldcupjson.net/matches?details=true in your browser and see if you can see the JSON data

**Comment by EmbeddedBacon** [comment]
Tried loading the page as document and found out the site is being blocked by a proxy here at work.   Will close this ticket.
