### ISSUE TITLE
Goals incorrect ?

### ISSUE THREAD

**Issue by bakman2** [cedricblondeau/world-cup-2022-cli-dashboard#17]
NED-QAT was 2-0:

Why do we see this ?
```
Cody Gakpo 26' Goal 
Frenkie De Jong 49' Goal
Frenkie De Jong 50' Goal 
Steven Berghuis 68' Goal    
```

**Comment by cedricblondeau** [comment]
This is an issue with the [worldcupjson.net](https://worldcupjson.net/) API.

<img width="286" alt="Screenshot 2022-11-30 at 9 38 12 AM" src="https://user-images.githubusercontent.com/1479924/204747735-13d08856-b187-4aa2-a300-877f36a4b5f8.png">

Please feel free to report this bug in [world_cup_json/issues](https://github.com/estiens/world_cup_json/issues).
