### ISSUE TITLE
Inaccurate result - source may be wrong

### ISSUE THREAD

**Issue by netfortius** [cedricblondeau/world-cup-2022-cli-dashboard#20]
Source may be inaccurate: Tunisie - France ended 1-0, not 1-1
<img width="832" alt="Screenshot 2022-11-30 at 20 43 26" src="https://user-images.githubusercontent.com/208389/204893523-34ad64ba-de6a-4772-b740-3a388350b009.png">

**Comment by muesli** [comment]
Confirmed, this is incorrectly reported by worldcupjson.net.
