### ISSUE TITLE
Duplicate goals.

### ISSUE THREAD

**Issue by ngacho** [cedricblondeau/world-cup-2022-cli-dashboard#21]
For certain games, the tool shows duplicate goals, see attached image. 
<img width="1134" alt="Screenshot 2022-12-01 at 10 45 02 AM" src="https://user-images.githubusercontent.com/52356809/205096729-1a845a93-bcd2-4ac0-90d8-48de2da172c1.png">

**Comment by DannyJJK** [comment]
This is a problem with https://worldcupjson.net, not with this tool.

See data provided by https://worldcupjson.net/matches/39 (Match ID 39 is Poland V Argentina)

Look at the `away_team_events`. You can use either Firefox or a JSON file viewer to view the data in a nicer way.

**Comment by ngacho** [comment]
Fair enough.

Thank you for the awesome tool mate :)
Regards,
*Ngacho*.

*"A painting is never finished-It simply stops in interesting places."*
Paul Gauguin.

**Comment by cedricblondeau** [comment]
This is an issue with the [worldcupjson.net](https://worldcupjson.net/) API.

See https://github.com/estiens/world_cup_json/issues/231.
